repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.3
    hooks:
      - id: uv-lock
        name: "Ensure lock file is up-to-date"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        name: "Organize imports"
        args: [check, --select, I, --fix]
      - id: ruff-check
        name: "Lint with ruff"
        args: [--fix]
      - id: ruff-format
        name: "Format with ruff"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: "Check for type consistency"
        exclude: "^(build/|tests/)"
        args: [
          "--python-version=3.14",
          "--ignore-missing-imports",
          "--strict",
          "--warn-unused-configs"
        ]

  - repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: .venv/bin/pytest
        language: script
        pass_filenames: false
        always_run: true

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.19.2
    hooks:
      - id: renovate-config-validator
        args: [--strict]
        files: ^renovate\.json$
